import type { EventInfo, Person, Role, Signals, Stage } from '@/lib/types';
import type { GoalId } from '@/lib/types';

interface Seed {
  n: string;
  h: string;
  r: Role;
  c: string;
  loc: string;
  seek: GoalId[];
  offer: GoalId[];
  sk: string[];
  ind: string[];
  st: Stage;
  int: string[];
  ask: string;
  give: string;
  hook: string;
  bio: string;
}

/**
 * The room.
 *
 * The first twelve seeds are the demo's headline matches, curated against the
 * guest profile in lib/demo.ts (Bangalore, prototype stage, seeking co-founder /
 * funding / customers, offering co-founding / collaboration / lessons, skilled
 * in backend, ML, infra and product management, into running, chess, open source
 * and coffee).
 *
 * They are built so every scored component lands high: complementary skills the
 * guest does not list, industries drawn from the guest's three, interests drawn
 * from the guest's four, a stage within one step of prototype and a shared home
 * city — which puts each of them between 90 and 98 out of 100 under the weights
 * in lib/matching.ts (goals 30, skills 18, industry 15, interests 13, stage 12,
 * location 8). The spread is deliberate: one component is dialled back per
 * person so the ranking has real texture instead of a wall of identical scores.
 *
 * Everything from Amara Osei onwards is the wider, unturned cohort.
 */
const SEEDS: Seed[] = [
  {
    n: 'Meera Iyer',
    h: 'Founder, Loomstack — looking for a technical co-founder',
    r: 'founder',
    c: 'Loomstack',
    loc: 'Bangalore',
    seek: ['cofounder', 'funding', 'customers'],
    offer: ['cofounder', 'collaborate', 'learn'],
    sk: ['Product design', 'Product management', 'Growth marketing', 'Content'],
    ind: ['AI infrastructure', 'Developer tools'],
    st: 'prototype',
    int: ['Chess', 'Coffee', 'Open source'],
    ask: 'A backend and infra co-founder who has run model serving in production.',
    give: 'Product and design leadership, plus 300 warm developer users already testing.',
    hook: 'shipped a prototype to 300 developers in six weeks with no engineering hire',
    bio: 'Ex-product lead turned founder. Has the users and the design, needs the systems half of the company.',
  },
  {
    n: 'Rohan Desai',
    h: 'Principal, Meridian South (pre-seed AI infrastructure)',
    r: 'investor',
    c: 'Meridian South',
    loc: 'Bangalore',
    seek: ['invest', 'collaborate'],
    offer: ['invest', 'mentee', 'collaborate'],
    sk: ['Fundraising', 'Finance', 'Enterprise sales', 'Operations'],
    ind: ['AI infrastructure', 'Developer tools'],
    st: 'none',
    int: ['Chess', 'Long-distance running'],
    ask: 'Prototype-stage infra teams in India with a working system and real usage.',
    give: 'First cheques of $300k–900k and a standing intro list of 60 platform buyers.',
    hook: 'wrote the first cheque into four Indian developer-tool companies, three now at Series A',
    bio: 'Invests only where he can read the code review. Prefers founders who ship before they pitch.',
  },
  {
    n: 'Ananya Kulkarni',
    h: 'Design lead, ex-Razorpay — open to co-founding',
    r: 'designer',
    c: 'Independent',
    loc: 'Mumbai',
    seek: ['cofounder', 'funding'],
    offer: ['cofounder', 'collaborate', 'mentee'],
    sk: ['Product design', 'Brand design', 'Growth marketing', 'Content'],
    ind: ['Developer tools', 'AI infrastructure'],
    st: 'prototype',
    int: ['Open source', 'Coffee', 'Chess'],
    ask: 'A technical founder who wants design as a founding function, not a contract.',
    give: 'End-to-end product design and the brand work that made a fintech app feel trustworthy.',
    hook: 'designed the onboarding that took a fintech from 31% to 68% activation',
    bio: 'Ten years designing developer and money products. Ready to own design as a founder.',
  },
  {
    n: 'Vikram Nair',
    h: 'VP Engineering, Trellis Data',
    r: 'engineer',
    c: 'Trellis Data',
    loc: 'Bangalore',
    seek: ['cofounder', 'customers'],
    offer: ['cofounder', 'hiring', 'learn'],
    sk: ['Data engineering', 'Security', 'Operations'],
    ind: ['AI infrastructure', 'Fintech'],
    st: 'pre-seed',
    int: ['Long-distance running', 'Coffee'],
    ask: 'A second founder for the spin-out I keep sketching, and design partners for it.',
    give: 'Hard detail on running regulated data pipelines, plus two open staff roles.',
    hook: 'built the pipeline that clears 40m regulated transactions a day',
    bio: 'Runs a 30-person platform group. Wants to leave and start the security tooling company he needed.',
  },
  {
    n: 'Sana Qureshi',
    h: 'Angel investor and operator-in-residence',
    r: 'investor',
    c: 'Qureshi Capital',
    loc: 'Bangalore',
    seek: ['collaborate', 'invest'],
    offer: ['invest', 'mentee', 'collaborate'],
    sk: ['Fundraising', 'Legal & compliance', 'Finance', 'Community building'],
    ind: ['Fintech', 'AI infrastructure'],
    st: 'none',
    int: ['Chess', 'Coffee'],
    ask: 'Technical founders in fintech or AI tooling who want an angel who answers on a Sunday.',
    give: '$50k–150k angel cheques, plus the compliance playbook for shipping money products in India.',
    hook: 'took a payments product through RBI licensing twice',
    bio: 'Angel investor with an operator past. Writes small cheques and does unreasonable amounts of work for them.',
  },
  {
    n: 'Kabir Menon',
    h: 'Co-founder, Tesseract — pre-seed dev tools',
    r: 'founder',
    c: 'Tesseract',
    loc: 'Bangalore',
    seek: ['cofounder', 'customers'],
    offer: ['cofounder', 'collaborate'],
    sk: ['Frontend engineering', 'Product design', 'Growth marketing', 'Content'],
    ind: ['Developer tools', 'AI infrastructure'],
    st: 'pre-seed',
    int: ['Open source', 'Coffee', 'Bouldering'],
    ask: 'A third founder on infrastructure, and teams who will run our agent tooling for real.',
    give: 'Distribution: our newsletter reaches 22k engineers who actually open it.',
    hook: 'grew a developer newsletter to 22k subscribers before writing any product code',
    bio: 'Builds in public. Strong on interface and audience, thin on the systems underneath.',
  },
  {
    n: 'Ishita Bose',
    h: 'Research engineer, Indian Institute of Science',
    r: 'researcher',
    c: 'IISc',
    loc: 'Bangalore',
    seek: ['cofounder', 'funding'],
    offer: ['cofounder', 'collaborate', 'learn'],
    sk: ['Clinical research', 'Data engineering', 'Hardware', 'Machine learning'],
    ind: ['AI infrastructure', 'Health tech', 'Developer tools'],
    st: 'prototype',
    int: ['Chess', 'Open source', 'Coffee'],
    ask: 'A co-founder who can turn a research prototype into a product people pay for.',
    give: 'Three years of published work on efficient inference on cheap hardware.',
    hook: 'published an inference method that runs a 7b model on a $40 board',
    bio: 'Academic who wants to commercialise. Needs someone who has shipped to users, not reviewers.',
  },
  {
    n: 'Arjun Balan',
    h: 'Head of Growth, Pier — building on the side',
    r: 'growth',
    c: 'Pier',
    loc: 'Bangalore',
    seek: ['cofounder', 'funding', 'customers'],
    offer: ['cofounder', 'collaborate', 'learn'],
    sk: ['Growth marketing', 'Content', 'Enterprise sales', 'Community building'],
    ind: ['Fintech', 'Developer tools'],
    st: 'pre-seed',
    int: ['Long-distance running', 'Coffee', 'Live music'],
    ask: 'A technical co-founder so I can quit and do this properly.',
    give: 'I have taken two products from zero to first paying cohort. I know where the demand is.',
    hook: 'took a fintech from 0 to 4,000 paying businesses in fourteen months',
    bio: 'Growth operator with a half-built side product and a very short list of people he would start a company with.',
  },
  {
    n: 'Neha Kapoor',
    h: 'COO, Northline — hiring and advising',
    r: 'operator',
    c: 'Northline',
    loc: 'Bangalore',
    seek: ['cofounder', 'hiring'],
    offer: ['cofounder', 'hiring', 'mentee'],
    sk: ['Operations', 'Recruiting', 'Supply chain', 'Finance'],
    ind: ['AI infrastructure', 'Developer tools'],
    st: 'seed',
    int: ['Long-distance running', 'Coffee'],
    ask: 'A technical co-founder for the spin-out, and two senior infrastructure engineers.',
    give: 'The hiring loop we use to close senior engineers in under three weeks.',
    hook: 'scaled a team from 8 to 74 without a single senior hire leaving inside a year',
    bio: 'Operator who fixes the unglamorous machinery. Open to co-founding if the technical half is right.',
  },
  {
    n: 'Farhan Sheikh',
    h: 'Staff engineer, Cred — prototyping nights and weekends',
    r: 'engineer',
    c: 'Cred',
    loc: 'Bangalore',
    seek: ['cofounder', 'funding'],
    offer: ['cofounder', 'collaborate', 'learn'],
    sk: ['Mobile engineering', 'Frontend engineering', 'Security', 'Data engineering'],
    ind: ['Developer tools', 'Fintech'],
    st: 'idea',
    int: ['Open source', 'Chess', 'Coffee', 'Long-distance running'],
    ask: 'Someone to build the backend half of an idea I have been circling for a year.',
    give: 'Mobile and client work at production quality, and payments security experience.',
    hook: 'owns the mobile security layer used by 11m people daily',
    bio: 'Client-side specialist looking for the server-side other half. Wants to start before he turns 34.',
  },
  {
    n: 'Divya Raman',
    h: 'Product designer, ex-Zerodha',
    r: 'designer',
    c: 'Independent',
    loc: 'Bangalore',
    seek: ['cofounder', 'job'],
    offer: ['cofounder', 'collaborate'],
    sk: ['Product design', 'Brand design', 'Frontend engineering'],
    ind: ['Developer tools', 'AI infrastructure'],
    st: 'prototype',
    int: ['Chess', 'Coffee', 'Open source'],
    ask: 'A founding team where design decides things, or a founding designer role.',
    give: 'Design that ships — I build my own front end rather than handing over files.',
    hook: 'designed and shipped the front end of a trading app used by 2m people',
    bio: 'Designer who codes. Has turned down three agency offers waiting for a founding seat.',
  },
  {
    n: 'Aditya Rao',
    h: 'Advisor and angel, ex-founder (acquired)',
    r: 'advisor',
    c: 'Independent',
    loc: 'Bangalore',
    seek: ['collaborate', 'mentor'],
    offer: ['mentee', 'invest', 'collaborate'],
    sk: ['Enterprise sales', 'Fundraising', 'Legal & compliance', 'Operations'],
    ind: ['Fintech', 'Developer tools'],
    st: 'none',
    int: ['Chess', 'Coffee'],
    ask: 'Prototype-stage founders I can be useful to before there is a round to join.',
    give: 'Angel cheques, and the enterprise sales motion that got us acquired.',
    hook: 'sold his developer-tools company after reaching $6m ARR with four sales people',
    bio: 'Second-time-around: invests, advises, and is looking for the next thing to help build.',
  },
  {
    n: 'Amara Osei',
    h: 'Partner at Northsignal Ventures',
    r: 'investor',
    c: 'Northsignal Ventures',
    loc: 'Berlin',
    seek: ['invest', 'learn'],
    offer: ['invest', 'mentee'],
    sk: ['Fundraising', 'Finance'],
    ind: ['AI infrastructure', 'Developer tools'],
    st: 'none',
    int: ['Chess', 'Long-distance running'],
    ask: 'Pre-seed AI infrastructure teams with a technical founder already shipping to real users.',
    give: 'First cheques of €250k–750k plus intros to 40+ portfolio operators.',
    hook: 'led pre-seed rounds in two developer-tool companies that raised Series A within nine months',
    bio: 'Ten years investing in infrastructure. Writes the first institutional cheque and stays close through the first ten hires.',
  },
  {
    n: 'Tobias Lindqvist',
    h: 'Solo GP, Cadence Capital',
    r: 'investor',
    c: 'Cadence Capital',
    loc: 'Lisbon',
    seek: ['invest', 'collaborate'],
    offer: ['invest', 'mentee'],
    sk: ['Fundraising', 'Enterprise sales'],
    ind: ['Enterprise SaaS', 'Fintech'],
    st: 'none',
    int: ['Surfing', 'Coffee'],
    ask: 'Seed-stage B2B founders with a repeatable sales motion, not just a pilot.',
    give: 'Cheque plus a 200-company outbound list built from my own operator network.',
    hook: 'ran enterprise sales at two fintechs before raising a €40m solo fund',
    bio: 'Ex-sales leader turned solo GP. Obsessed with go-to-market mechanics at seed.',
  },
  {
    n: 'Priya Raghunathan',
    h: 'Co-founder & CTO, Halcyon Labs',
    r: 'founder',
    c: 'Halcyon Labs',
    loc: 'Bangalore',
    seek: ['funding', 'hiring'],
    offer: ['collaborate', 'mentee', 'learn'],
    sk: ['Machine learning', 'Infrastructure', 'Backend engineering'],
    ind: ['AI infrastructure', 'Developer tools'],
    st: 'seed',
    int: ['Open source', 'Bouldering'],
    ask: 'Intros to infra-focused seed funds and a senior inference engineer.',
    give: 'Deep detail on serving large models cheaply — we cut our own costs 71%.',
    hook: 'cut model-serving costs by 71% and open-sourced the scheduler behind it',
    bio: 'Builds the serving layer for teams that cannot afford a dedicated ML platform team.',
  },
  {
    n: 'Daniel Okafor',
    h: 'Founder, Ledgerly',
    r: 'founder',
    c: 'Ledgerly',
    loc: 'London',
    seek: ['cofounder', 'funding'],
    offer: ['cofounder', 'collaborate'],
    sk: ['Product management', 'Finance', 'Enterprise sales'],
    ind: ['Fintech', 'Enterprise SaaS'],
    st: 'prototype',
    int: ['Chess', 'Writing'],
    ask: 'A technical co-founder who has shipped payments infrastructure before.',
    give: 'Two signed design partners and a finance background that closes enterprise deals.',
    hook: 'signed two design partners before writing a line of production code',
    bio: 'Ex-treasury operator building reconciliation tooling for multi-entity finance teams.',
  },
  {
    n: 'Lena Fischer',
    h: 'Staff ML Engineer, Aurograph',
    r: 'engineer',
    c: 'Aurograph',
    loc: 'Berlin',
    seek: ['cofounder', 'learn'],
    offer: ['job', 'cofounder', 'collaborate'],
    sk: ['Machine learning', 'Data engineering', 'Infrastructure'],
    ind: ['AI infrastructure', 'Health tech'],
    st: 'idea',
    int: ['Open source', 'Cycling', 'Sci-fi'],
    ask: 'A commercial co-founder for a diagnostics idea I have been prototyping at night.',
    give: 'Production ML at scale, and I can build the first version alone.',
    hook: 'quietly prototyped a diagnostics model on weekends while shipping ML at scale by day',
    bio: 'Six years of production machine learning. Wants to start something in the next six months.',
  },
  {
    n: 'Marcus Bell',
    h: 'Head of Platform, Ridgeway Health',
    r: 'operator',
    c: 'Ridgeway Health',
    loc: 'New York',
    seek: ['learn', 'hiring'],
    offer: ['customers', 'mentee', 'job'],
    sk: ['Operations', 'Infrastructure', 'Security'],
    ind: ['Health tech', 'Enterprise SaaS'],
    st: 'growth',
    int: ['Board games', 'Cooking'],
    ask: 'Tooling that shortens our vendor security review from twelve weeks to two.',
    give: 'A real buying budget and a candid account of how health systems actually procure.',
    hook: 'signs off on vendor security reviews for a 40-hospital network',
    bio: 'Runs platform and vendor strategy. The person most health-tech founders actually need to convince.',
  },
  {
    n: 'Sofia Marchetti',
    h: 'Founder & CEO, Verdant Grid',
    r: 'founder',
    c: 'Verdant Grid',
    loc: 'Amsterdam',
    seek: ['funding', 'customers'],
    offer: ['collaborate', 'mentee'],
    sk: ['Hardware', 'Supply chain', 'Operations'],
    ind: ['Climate', 'Logistics'],
    st: 'pre-seed',
    int: ['Cycling', 'Photography'],
    ask: 'Climate-focused pre-seed investors and two pilot sites in the Netherlands.',
    give: 'Hardware supply-chain scars — I can save you six months of sourcing mistakes.',
    hook: 'brought a grid-storage unit from CAD to a working pilot in seven months',
    bio: 'Ex-industrial engineer building distributed storage for commercial buildings.',
  },
  {
    n: 'Yusuf Demir',
    h: 'Design lead, freelance',
    r: 'designer',
    c: 'Independent',
    loc: 'Berlin',
    seek: ['collaborate', 'job'],
    offer: ['collaborate', 'job', 'mentee'],
    sk: ['Product design', 'Brand design'],
    ind: ['Consumer social', 'Creator economy', 'Developer tools'],
    st: 'none',
    int: ['Live music', 'Photography', 'Coffee'],
    ask: 'A founding-design role or a serious long-term product partnership.',
    give: 'End-to-end product design, and I ship in code as well as Figma.',
    hook: 'designed and front-end-built three products that each crossed 100k users',
    bio: 'Independent design lead who has been the first designer at three startups.',
  },
  {
    n: 'Hannah Weiss',
    h: 'Founder, Tandem Learning',
    r: 'founder',
    c: 'Tandem Learning',
    loc: 'Berlin',
    seek: ['cofounder', 'customers'],
    offer: ['cofounder', 'collaborate', 'learn'],
    sk: ['Content', 'Community building', 'Product management'],
    ind: ['Education', 'Consumer social'],
    st: 'prototype',
    int: ['Language learning', 'Writing', 'Coffee'],
    ask: 'A technical co-founder and 20 teachers willing to test weekly.',
    give: 'A 9,000-member teacher community that gives feedback within hours.',
    hook: 'built a 9,000-member teacher community before building any product',
    bio: 'Former teacher building peer-to-peer language practice that people actually finish.',
  },
  {
    n: 'Rajiv Menon',
    h: 'Angel investor & former founder',
    r: 'investor',
    c: 'Independent',
    loc: 'Singapore',
    seek: ['invest', 'mentee'],
    offer: ['invest', 'mentee'],
    sk: ['Fundraising', 'Growth marketing', 'Product management'],
    ind: ['Marketplaces', 'Consumer social', 'Fintech'],
    st: 'none',
    int: ['Ultramarathons', 'Cooking'],
    ask: 'Marketplace founders at the awkward stage between prototype and product-market fit.',
    give: '€25k–100k angel cheques and hands-on help with liquidity problems.',
    hook: 'scaled a marketplace to $180m GMV, then sold it and started angel investing',
    bio: 'Exited marketplace founder. Now writes small cheques and shows up for the hard weeks.',
  },
  {
    n: 'Elin Sørensen',
    h: 'VP Engineering, Kestrel Security',
    r: 'engineer',
    c: 'Kestrel Security',
    loc: 'London',
    seek: ['hiring', 'learn'],
    offer: ['job', 'mentee', 'customers'],
    sk: ['Security', 'Backend engineering', 'Recruiting'],
    ind: ['Cybersecurity', 'Enterprise SaaS'],
    st: 'growth',
    int: ['Bouldering', 'Sci-fi'],
    ask: 'Two senior backend engineers who like unglamorous, correct systems.',
    give: 'Honest feedback on your security posture before an enterprise buyer finds the holes.',
    hook: 'has reviewed the security posture of over 300 startups as a buyer and a vendor',
    bio: 'Runs a 45-person engineering org. Hires slowly and keeps people for years.',
  },
  {
    n: 'Chidi Nwosu',
    h: 'Founder, Cargolane',
    r: 'founder',
    c: 'Cargolane',
    loc: 'Lisbon',
    seek: ['funding', 'hiring'],
    offer: ['collaborate', 'mentee'],
    sk: ['Supply chain', 'Operations', 'Enterprise sales'],
    ind: ['Logistics', 'Marketplaces'],
    st: 'seed',
    int: ['Long-distance running', 'Board games'],
    ask: 'Seed extension investors and a first growth hire for freight forwarders.',
    give: 'How to sell software to freight forwarders who still run on spreadsheets.',
    hook: 'sold logistics software to 60 freight forwarders without a single demo call',
    bio: 'Building the operating system for mid-sized freight forwarders in Europe.',
  },
  {
    n: 'Nora Haddad',
    h: 'Product Manager, Northwind Bank',
    r: 'product',
    c: 'Northwind Bank',
    loc: 'Paris',
    seek: ['job', 'mentor'],
    offer: ['customers', 'job', 'collaborate'],
    sk: ['Product management', 'Legal & compliance', 'Finance'],
    ind: ['Fintech', 'Enterprise SaaS'],
    st: 'none',
    int: ['Chess', 'Cooking', 'Writing'],
    ask: 'A move into an early-stage fintech, and someone who has made that jump before.',
    give: 'How a regulated bank actually evaluates and buys a fintech vendor.',
    hook: 'ran the vendor selection for a core banking migration at a regulated bank',
    bio: 'Regulated-fintech product manager who wants a smaller room and a faster clock.',
  },
  {
    n: 'Felix Braun',
    h: 'Co-founder, Straylight Robotics',
    r: 'founder',
    c: 'Straylight Robotics',
    loc: 'Berlin',
    seek: ['funding', 'collaborate'],
    offer: ['collaborate', 'mentee', 'learn'],
    sk: ['Hardware', 'Machine learning', 'Infrastructure'],
    ind: ['Robotics', 'Logistics'],
    st: 'pre-seed',
    int: ['Woodworking', 'Sci-fi', 'Open source'],
    ask: 'Deep-tech investors comfortable with a 24-month hardware timeline.',
    give: 'Practical robotics perception advice and a very well-equipped workshop.',
    hook: 'built a warehouse picking arm that runs unattended for eleven hours',
    bio: 'Robotics engineer building picking automation for mid-sized warehouses.',
  },
  {
    n: 'Isabel Cortez',
    h: 'Head of Growth, Pulsewave',
    r: 'growth',
    c: 'Pulsewave',
    loc: 'Barcelona',
    seek: ['job', 'collaborate'],
    offer: ['mentee', 'job', 'collaborate'],
    sk: ['Growth marketing', 'Content', 'Community building'],
    ind: ['Consumer social', 'Creator economy'],
    st: 'growth',
    int: ['Live music', 'Surfing', 'Photography'],
    ask: 'A founding growth role at something with real consumer pull.',
    give: 'Zero-to-one growth playbooks that do not rely on paid acquisition.',
    hook: 'grew a consumer app from 12k to 900k users with no paid budget',
    bio: 'Consumer growth operator. Believes distribution is a product problem.',
  },
  {
    n: 'Arjun Kapoor',
    h: 'Founder, Nimbus Health',
    r: 'founder',
    c: 'Nimbus Health',
    loc: 'Bangalore',
    seek: ['customers', 'funding'],
    offer: ['collaborate', 'mentee'],
    sk: ['Clinical research', 'Product management', 'Machine learning'],
    ind: ['Health tech', 'AI infrastructure'],
    st: 'seed',
    int: ['Long-distance running', 'Coffee'],
    ask: 'Hospital operators willing to run a six-week triage pilot.',
    give: 'What it actually takes to get clinical validation without burning a year.',
    hook: 'got a triage model through clinical validation in five months',
    bio: 'Clinician-turned-founder building triage support for overloaded emergency departments.',
  },
  {
    n: 'Greta Novak',
    h: 'Angel & operating advisor',
    r: 'advisor',
    c: 'Independent',
    loc: 'Amsterdam',
    seek: ['invest', 'mentee'],
    offer: ['invest', 'mentee'],
    sk: ['Operations', 'Recruiting', 'Finance'],
    ind: ['Enterprise SaaS', 'Health tech', 'Climate'],
    st: 'none',
    int: ['Cycling', 'Cooking', 'Chess'],
    ask: 'Seed founders about to make their first ten hires and dreading it.',
    give: 'Hiring systems, comp structures, and small cheques.',
    hook: 'built the hiring machine that took a Series A company from 15 to 180 people',
    bio: 'Former COO. Now angel investing and advising on the messy people layer.',
  },
  {
    n: 'Kofi Mensah',
    h: 'Founder, Statecraft',
    r: 'founder',
    c: 'Statecraft',
    loc: 'London',
    seek: ['cofounder', 'customers'],
    offer: ['cofounder', 'collaborate', 'learn'],
    sk: ['Backend engineering', 'Infrastructure', 'Security'],
    ind: ['Developer tools', 'Cybersecurity'],
    st: 'prototype',
    int: ['Open source', 'Chess', 'Bouldering'],
    ask: 'A go-to-market co-founder — I can build, I cannot sell.',
    give: 'A working product, deep systems knowledge, and no ego about titles.',
    hook: 'shipped a working infrastructure product alone in four months',
    bio: 'Systems engineer building policy-as-code tooling for platform teams.',
  },
  {
    n: 'Camille Rousseau',
    h: 'Principal, Meridian Growth',
    r: 'investor',
    c: 'Meridian Growth',
    loc: 'Paris',
    seek: ['invest'],
    offer: ['invest', 'mentee'],
    sk: ['Finance', 'Enterprise sales', 'Fundraising'],
    ind: ['Climate', 'Logistics', 'Enterprise SaaS'],
    st: 'none',
    int: ['Photography', 'Cooking'],
    ask: 'Series A climate and logistics companies with more than €1m of revenue.',
    give: 'A clear read on whether you are actually Series A ready, and why not.',
    hook: 'has run diligence on 400 climate companies and funded eleven',
    bio: 'Growth-stage investor. Blunt about metrics, generous with time.',
  },
  {
    n: 'Oskar Nowak',
    h: 'Senior Mobile Engineer, Tetherline',
    r: 'engineer',
    c: 'Tetherline',
    loc: 'Warsaw',
    seek: ['job', 'cofounder'],
    offer: ['job', 'collaborate'],
    sk: ['Mobile engineering', 'Frontend engineering'],
    ind: ['Consumer social', 'Gaming', 'Developer tools'],
    st: 'idea',
    int: ['Gaming', 'Board games', 'Cycling'],
    ask: 'A founding mobile role, or a founder who needs an app built properly.',
    give: 'Shipping-quality mobile work and a very high tolerance for ambiguity.',
    hook: 'has shipped eleven apps to the App Store, four of them solo',
    bio: 'Mobile engineer who cares about the first-run experience more than the architecture diagram.',
  },
  {
    n: 'Mira Solberg',
    h: 'Founder, Kelpline',
    r: 'founder',
    c: 'Kelpline',
    loc: 'Oslo',
    seek: ['funding', 'mentor'],
    offer: ['collaborate', 'learn'],
    sk: ['Supply chain', 'Operations', 'Clinical research'],
    ind: ['Climate', 'Logistics'],
    st: 'idea',
    int: ['Surfing', 'Cooking', 'Photography'],
    ask: 'A mentor who has taken a physical product from idea to first revenue.',
    give: 'Ocean supply-chain access most climate founders cannot get.',
    hook: 'secured harvesting rights along 40km of coastline before incorporating',
    bio: 'Marine biologist building seaweed-based packaging inputs.',
  },
  {
    n: 'Ben Ashford',
    h: 'CTO, Loomwork',
    r: 'engineer',
    c: 'Loomwork',
    loc: 'Toronto',
    seek: ['hiring', 'learn'],
    offer: ['mentee', 'job', 'customers'],
    sk: ['Backend engineering', 'Data engineering', 'Infrastructure'],
    ind: ['Enterprise SaaS', 'Developer tools'],
    st: 'series-a',
    int: ['Woodworking', 'Coffee', 'Open source'],
    ask: 'A data platform lead, and better internal tooling for our own team.',
    give: 'A budget for developer tools and honest procurement feedback.',
    hook: 'buys developer tooling for a 90-engineer organisation',
    bio: 'Series A CTO. Will tell you in ten minutes whether your dev tool would survive his stack.',
  },
  {
    n: 'Aiko Tanaka',
    h: 'Research scientist, Kyoto Institute',
    r: 'researcher',
    c: 'Kyoto Institute',
    loc: 'Kyoto',
    seek: ['cofounder', 'collaborate'],
    offer: ['cofounder', 'collaborate', 'mentee'],
    sk: ['Machine learning', 'Clinical research', 'Data engineering'],
    ind: ['Health tech', 'AI infrastructure'],
    st: 'idea',
    int: ['Writing', 'Language learning', 'Chess'],
    ask: 'A commercial co-founder to take three years of research out of the lab.',
    give: 'Novel methods, published and reproducible, plus academic credibility.',
    hook: 'has three papers on medical imaging that nobody has commercialised yet',
    bio: 'Research scientist looking for the right person to build a company around her work.',
  },
  {
    n: 'Tomás Rivera',
    h: 'Founder, Bracket',
    r: 'founder',
    c: 'Bracket',
    loc: 'Madrid',
    seek: ['customers', 'collaborate'],
    offer: ['collaborate', 'learn', 'customers'],
    sk: ['Frontend engineering', 'Product design', 'Growth marketing'],
    ind: ['Creator economy', 'Consumer social'],
    st: 'pre-seed',
    int: ['Live music', 'Gaming', 'Writing'],
    ask: 'Creators with over 50k followers who will test monetisation with us.',
    give: 'Consumer front-end craft and fast iteration on paid conversion.',
    hook: 'shipped 41 releases in his first quarter and doubled paid conversion',
    bio: 'Solo founder building monetisation tools for mid-sized creators.',
  },
  {
    n: 'Sara Lindberg',
    h: 'Talent Partner, Hollowbrook Capital',
    r: 'operator',
    c: 'Hollowbrook Capital',
    loc: 'Stockholm',
    seek: ['hiring', 'collaborate'],
    offer: ['job', 'mentee', 'collaborate'],
    sk: ['Recruiting', 'Operations', 'Community building'],
    ind: ['Enterprise SaaS', 'Fintech', 'Developer tools'],
    st: 'none',
    int: ['Long-distance running', 'Coffee'],
    ask: 'Founding engineers and designers for eight portfolio companies hiring now.',
    give: 'Direct intros to portfolio founders who have live roles and real budgets.',
    hook: 'places founding engineers into eight portfolio companies at once',
    bio: 'Talent partner at a seed fund. The fastest route to a founding-team role in this room.',
  },
  {
    n: 'Wei Zhang',
    h: 'Founder & CEO, Threadbare',
    r: 'founder',
    c: 'Threadbare',
    loc: 'Singapore',
    seek: ['funding', 'hiring'],
    offer: ['mentee', 'collaborate'],
    sk: ['Growth marketing', 'Enterprise sales', 'Operations'],
    ind: ['Marketplaces', 'Logistics'],
    st: 'series-a',
    int: ['Cycling', 'Cooking', 'Board games'],
    ask: 'Series A investors in Europe and a regional GM for the EU market.',
    give: 'How to run a marketplace across five countries without losing unit economics.',
    hook: 'runs a marketplace across five countries at positive contribution margin',
    bio: 'Series A marketplace founder expanding from Asia into Europe.',
  },
  {
    n: 'Julia Kowalski',
    h: 'Product designer, Northsignal portfolio',
    r: 'designer',
    c: 'Independent',
    loc: 'Berlin',
    seek: ['collaborate', 'mentor'],
    offer: ['collaborate', 'job'],
    sk: ['Product design', 'Brand design', 'Content'],
    ind: ['Health tech', 'Education'],
    st: 'none',
    int: ['Photography', 'Bouldering', 'Writing'],
    ask: 'A design mentor working at a larger scale than I am.',
    give: 'Fast, opinionated product design for early teams with no design function.',
    hook: 'redesigned onboarding for four seed companies and lifted activation each time',
    bio: 'Product designer embedded across a seed fund portfolio.',
  },
  {
    n: 'Ethan Cole',
    h: 'Founder, Signalfire Analytics',
    r: 'founder',
    c: 'Signalfire Analytics',
    loc: 'New York',
    seek: ['customers', 'cofounder'],
    offer: ['collaborate', 'cofounder', 'learn'],
    sk: ['Data engineering', 'Machine learning', 'Product management'],
    ind: ['Developer tools', 'AI infrastructure', 'Enterprise SaaS'],
    st: 'prototype',
    int: ['Sci-fi', 'Chess', 'Coffee'],
    ask: 'Engineering leaders who will trial an observability tool this quarter.',
    give: 'Deep experience turning noisy telemetry into something people act on.',
    hook: 'built the internal observability stack for a company running 4,000 services',
    bio: 'Data engineer building observability that does not require a dedicated team to operate.',
  },
  {
    n: 'Nadia Rahman',
    h: 'Programme Director, FutureSkills',
    r: 'operator',
    c: 'FutureSkills',
    loc: 'London',
    seek: ['collaborate', 'customers'],
    offer: ['customers', 'collaborate', 'mentee'],
    sk: ['Operations', 'Community building', 'Content'],
    ind: ['Education', 'Enterprise SaaS'],
    st: 'growth',
    int: ['Writing', 'Language learning', 'Cooking'],
    ask: 'Education tools we can put in front of 30,000 learners next term.',
    give: 'Distribution to 30,000 learners and a procurement process I control.',
    hook: 'controls a distribution channel of 30,000 active learners',
    bio: 'Runs a national skills programme. Buys and distributes education software at scale.',
  },
  {
    n: 'Lucas Meyer',
    h: 'Founder, Stonefold',
    r: 'founder',
    c: 'Stonefold',
    loc: 'Zurich',
    seek: ['mentor', 'funding'],
    offer: ['collaborate', 'learn'],
    sk: ['Finance', 'Legal & compliance', 'Product management'],
    ind: ['Fintech', 'Climate'],
    st: 'idea',
    int: ['Cycling', 'Chess', 'Woodworking'],
    ask: 'A mentor who has navigated financial licensing in the EU.',
    give: 'A rigorous grasp of carbon accounting rules most founders find opaque.',
    hook: 'read every EU carbon disclosure rule so his customers do not have to',
    bio: 'Ex-banker building carbon accounting for mid-market manufacturers.',
  },
  {
    n: 'Zara Ibrahim',
    h: 'Engineering student & hackathon regular',
    r: 'student',
    c: 'TU Berlin',
    loc: 'Berlin',
    seek: ['mentor', 'job'],
    offer: ['job', 'collaborate', 'learn'],
    sk: ['Frontend engineering', 'Mobile engineering', 'Machine learning'],
    ind: ['Consumer social', 'Developer tools', 'Gaming'],
    st: 'none',
    int: ['Gaming', 'Open source', 'Bouldering'],
    ask: 'A mentor and a first serious internship at a startup.',
    give: 'Relentless energy and four hackathon wins worth of shipping speed.',
    hook: 'won four hackathons in a year while finishing a degree',
    bio: 'Final-year engineering student who ships fast and wants a real team.',
  },
  {
    n: 'Henrik Dahl',
    h: 'Operating Partner, Vantage Industrial',
    r: 'advisor',
    c: 'Vantage Industrial',
    loc: 'Copenhagen',
    seek: ['invest', 'mentee'],
    offer: ['invest', 'mentee', 'customers'],
    sk: ['Supply chain', 'Operations', 'Finance'],
    ind: ['Climate', 'Robotics', 'Logistics'],
    st: 'none',
    int: ['Woodworking', 'Long-distance running'],
    ask: 'Hardware and climate founders who need industrial customers, not just capital.',
    give: 'Introductions to twelve industrial groups that pilot new technology.',
    hook: 'opens doors to twelve industrial groups that actually run pilots',
    bio: 'Operating partner focused on industrial adoption of climate and robotics technology.',
  },
  {
    n: 'Clara Nunes',
    h: 'Founder, Mosaic Care',
    r: 'founder',
    c: 'Mosaic Care',
    loc: 'Lisbon',
    seek: ['hiring', 'customers'],
    offer: ['mentee', 'collaborate'],
    sk: ['Clinical research', 'Operations', 'Product management'],
    ind: ['Health tech', 'Education'],
    st: 'seed',
    int: ['Cooking', 'Live music', 'Writing'],
    ask: 'A clinical operations lead and three more care providers to pilot with.',
    give: 'A hard-won map of health-care procurement in southern Europe.',
    hook: 'onboarded 30 care providers in a market everyone said moved too slowly',
    bio: 'Seed-stage founder building coordination software for community care teams.',
  },
  {
    n: 'Samuel Adeyemi',
    h: 'Platform Engineer, Volta Systems',
    r: 'engineer',
    c: 'Volta Systems',
    loc: 'Amsterdam',
    seek: ['cofounder', 'learn'],
    offer: ['cofounder', 'job', 'collaborate'],
    sk: ['Infrastructure', 'Backend engineering', 'Security'],
    ind: ['Climate', 'AI infrastructure'],
    st: 'idea',
    int: ['Cycling', 'Sci-fi', 'Board games'],
    ask: 'A co-founder who understands energy markets — I will handle the platform.',
    give: 'Infrastructure that stays up, and the discipline to keep scope small.',
    hook: 'kept a real-time energy platform at four nines for two years straight',
    bio: 'Platform engineer who wants to start a company in energy software.',
  },
  {
    n: 'Ines Baumann',
    h: 'Content lead & newsletter operator',
    r: 'growth',
    c: 'Independent',
    loc: 'Vienna',
    seek: ['collaborate', 'customers'],
    offer: ['customers', 'collaborate', 'mentee'],
    sk: ['Content', 'Growth marketing', 'Community building'],
    ind: ['Creator economy', 'Developer tools', 'Education'],
    st: 'none',
    int: ['Writing', 'Coffee', 'Live music'],
    ask: 'Tools worth writing about, and partners for a paid newsletter product.',
    give: 'A 60,000-subscriber audience of technical operators.',
    hook: 'writes to 60,000 technical operators every week',
    bio: 'Independent writer with distribution most seed companies would pay a lot for.',
  },
  {
    n: 'Diego Salvatierra',
    h: 'Co-founder, Puente Pay',
    r: 'founder',
    c: 'Puente Pay',
    loc: 'Mexico City',
    seek: ['funding', 'collaborate'],
    offer: ['collaborate', 'mentee', 'learn'],
    sk: ['Backend engineering', 'Finance', 'Legal & compliance'],
    ind: ['Fintech', 'Marketplaces'],
    st: 'pre-seed',
    int: ['Surfing', 'Cooking', 'Gaming'],
    ask: 'Pre-seed fintech investors comfortable with cross-border payments.',
    give: 'Payment rails knowledge across three regulatory regimes.',
    hook: 'built payment rails across three regulatory regimes with a team of four',
    bio: 'Payments engineer building cross-border settlement for small exporters.',
  },
  {
    n: 'Emma Larsen',
    h: 'Head of People, Brightfold',
    r: 'operator',
    c: 'Brightfold',
    loc: 'Copenhagen',
    seek: ['hiring', 'learn'],
    offer: ['job', 'mentee', 'customers'],
    sk: ['Recruiting', 'Operations', 'Legal & compliance'],
    ind: ['Enterprise SaaS', 'Education'],
    st: 'series-a',
    int: ['Cooking', 'Cycling', 'Board games'],
    ask: 'Engineering managers, and better tooling for distributed hiring.',
    give: 'Realistic comp benchmarks across seven European markets.',
    hook: 'holds comp benchmarks across seven European markets',
    bio: 'People lead at a Series A company. Hires across Europe every month.',
  },
  {
    n: 'Victor Petrov',
    h: 'Founder, Gridwatch',
    r: 'founder',
    c: 'Gridwatch',
    loc: 'Sofia',
    seek: ['customers', 'mentor'],
    offer: ['collaborate', 'learn'],
    sk: ['Data engineering', 'Machine learning', 'Infrastructure'],
    ind: ['Climate', 'AI infrastructure'],
    st: 'prototype',
    int: ['Chess', 'Open source', 'Photography'],
    ask: 'Utilities or industrial sites willing to run a forecasting pilot.',
    give: 'Forecasting models that beat the incumbent baseline by 18%.',
    hook: 'beat an incumbent grid forecasting baseline by 18% on public data',
    bio: 'Data scientist building demand forecasting for regional grid operators.',
  },
  {
    n: 'Leila Farah',
    h: 'Investment Associate, Kindling Fund',
    r: 'investor',
    c: 'Kindling Fund',
    loc: 'Dubai',
    seek: ['invest', 'learn'],
    offer: ['invest', 'mentee'],
    sk: ['Fundraising', 'Finance', 'Content'],
    ind: ['Education', 'Health tech', 'Consumer social'],
    st: 'none',
    int: ['Language learning', 'Photography', 'Coffee'],
    ask: 'Pre-seed founders in education and health, especially outside the usual hubs.',
    give: 'A fast yes or no, and a partner meeting within a week if it is a yes.',
    hook: 'moves from first meeting to term sheet in under two weeks',
    bio: 'Early-stage investor covering education and health in emerging markets.',
  },
];

function initialsOf(name: string): string {
  return name
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? '')
    .join('');
}

function toPerson(seed: Seed, index: number): Person {
  const signals: Signals = {
    seeking: seed.seek,
    offering: seed.offer,
    skills: seed.sk,
    industries: seed.ind,
    interests: seed.int,
    stage: seed.st,
    ask: seed.ask,
    give: seed.give,
  };

  return {
    id: `p${String(index + 1).padStart(2, '0')}`,
    name: seed.n,
    headline: seed.h,
    role: seed.r,
    company: seed.c,
    location: seed.loc,
    bio: seed.bio,
    hook: seed.hook,
    signals,
  };
}

export const ATTENDEES: Person[] = SEEDS.map(toPerson);

const ATTENDEE_BY_ID = new Map(ATTENDEES.map((person) => [person.id, person]));

export function findAttendee(id: string): Person | undefined {
  return ATTENDEE_BY_ID.get(id);
}

export function initials(name: string): string {
  return initialsOf(name);
}

export const CURRENT_EVENT: EventInfo = {
  id: 'ev-founder-frequency-2026',
  name: 'Founder Frequency Summit',
  tagline: 'Your next opportunity is in the room.',
  venue: 'Bangalore International Centre',
  city: 'Bangalore',
  dateLabel: 'Sat 1 Aug 2026',
  joinCode: 'BEAT26',
  cohortIndustries: [],
  cohortSize: ATTENDEES.length,
  isDemo: true,
  createdBy: null,
};

/**
 * Who is actually in a given room. Seeded events narrow the demo cohort by
 * industry focus; investors and advisors top up the smaller rooms because they
 * move between every event.
 */
export function cohortForEvent(event: EventInfo): Person[] {
  if (event.cohortIndustries.length === 0) {
    return ATTENDEES.slice(0, Math.max(1, event.cohortSize));
  }

  const focused = ATTENDEES.filter((person) =>
    person.signals.industries.some((industry) => event.cohortIndustries.includes(industry)),
  );
  const focusedIds = new Set(focused.map((person) => person.id));
  const connectors = ATTENDEES.filter(
    (person) =>
      !focusedIds.has(person.id) && (person.role === 'investor' || person.role === 'advisor'),
  );

  return [...focused, ...connectors].slice(0, Math.max(1, event.cohortSize));
}
